name: Deploy to Google Cloud Storage

on:
  push:
    branches:
    - master
    - develop

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  BUCKET_NAME: "gs://yann.work"

jobs:
  deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    - name: Deploy
      run: |-
        ls
        gsutil -m -h "Cache-Control:no-cache,max-age=0" \
          cp -r \
          *.html statics/ \
          $BUCKET_NAME
        gsutil web set -m index.html $BUCKET_NAME
        gsutil web set -e 404.html $BUCKET_NAME
